//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello911InfoViz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crimeEventLog
    {
        public int ID { get; set; }
        public long EventNumber { get; set; }
        public long GeneralOffenseNumber { get; set; }
        public int EventClearanceCode { get; set; }
        public string EventClearanceSubGroup { get; set; }
        public string EventClearanceGroup { get; set; }
        public Nullable<System.DateTime> EventClearanceDate { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
        public string Longitude { get; set; }
        public string Suburb { get; set; }
        public string Street { get; set; }
        public string Zipcode { get; set; }
        public string Latitude { get; set; }
        public string IncidentLocation { get; set; }
    }
}
